// Decompiled with JetBrains decompiler
// Type: FezEngine.Structure.ActorType
// Assembly: FezEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: BF0F94A8-07FE-4074-8978-FD18CC5EF662
// Assembly location: E:\GOG Games\Fez\FezEngine.dll

#nullable disable
namespace FezEngine.Structure;

public enum ActorType
{
  None,
  Ladder,
  Bouncer,
  Sign,
  GoldenCube,
  PickUp,
  Bomb,
  Destructible,
  DestructiblePermanent,
  Vase,
  Door,
  Heart,
  Watcher,
  Crystal,
  BlackHole,
  Vine,
  BigBomb,
  TntBlock,
  TntPickup,
  MotorBlock,
  Hurt,
  Checkpoint,
  TreasureChest,
  CubeShard,
  BigHeart,
  SkeletonKey,
  ExploSwitch,
  PushSwitch,
  EightBitDoor,
  PushSwitchSticky,
  PushSwitchPermanent,
  SuckBlock,
  WarpGate,
  OneBitDoor,
  SpinBlock,
  PivotHandle,
  FourBitDoor,
  LightningPlatform,
  LightningGhost,
  Tombstone,
  SplitUpCube,
  UnlockedDoor,
  Hole,
  Couch,
  Valve,
  Rumbler,
  Waterfall,
  Trickle,
  Drips,
  Geyser,
  ConnectiveRail,
  BoltHandle,
  BoltNutBottom,
  BoltNutTop,
  CodeMachine,
  NumberCube,
  LetterCube,
  TriSkull,
  Tome,
  SecretCube,
  LesserGate,
  Crumbler,
  LaserEmitter,
  LaserBender,
  LaserReceiver,
  RebuildingHexahedron,
  TreasureMap,
  Timeswitch,
  TimeswitchMovingPart,
  Mail,
  Mailbox,
  Bookcase,
  TwoBitDoor,
  SixteenBitDoor,
  ThirtyTwoBitDoor,
  SixtyFourBitDoor,
  Owl,
  Bell,
  RotatingGroup,
  BigWaterfall,
  Telescope,
  SinkPickup,
  QrCode,
  FpsPost,
  PieceOfHeart,
  SecretPassage,
  Piston,
}
